---
title: "Florida Law Help Website Analysis"
author: "Julia Park"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(readxl)
library(lubridate)

# Parameters
setwd("~/GitHub/Lab_Legal_Design/schema_eval/data")

file_search_performance = "Florida_Law_Help/search-performance.xlsx" 
file_visitors_overview = "Florida_Law_Help/visitors-overview(1).xlsx"

#===============================================================================

# Code
visitors_overview = read_excel(file_visitors_overview, skip = 6) %>% 
 filter(Segment == "All Users") %>% 
 filter(str_detect(`Date Range`, "2020"))
queries <- read_excel(file_search_performance, sheet = "Queries")
pages <- read_excel(file_search_performance, sheet = "Pages")
dates <- read_excel(file_search_performance, sheet = "Dates")

```

## Problems with Analytics

```{r}
visitors_overview %>% 
 top_n(15, `Week Index`)
```

## Visitors 

```{r}
dates %>% 
 ggplot(aes(x = Date, y = Clicks)) + 
 geom_line() + 
 geom_vline(xintercept = as.POSIXct(as.Date("2020-05-29")), color = "red") +
 geom_smooth(method = "loess") + 
 labs(
  title = "2020 daily visitors: Trend follows average visitor trend for this year"
 ) + 
 theme_minimal()
```


```{r}
dates %>% 
 ggplot(aes(x = Date, y = CTR)) + 
 geom_line() + 
 geom_vline(xintercept = as.POSIXct(as.Date("2020-05-29")), color = "red") +
 geom_smooth(method = "loess") +
 labs(
  title = "Click-through rate slightly increases after schema implementation", 
  subtitle = "Drastic loss/increase of visitors is due to search demand/seasonal changes"
 ) + 
 theme_minimal()
```


```{r}
dates %>% 
 ggplot(aes(x = Date, y = Position)) + 
 geom_line() + 
 geom_vline(xintercept = as.POSIXct(as.Date("2020-05-29")), color = "red") +
 geom_smooth(method = "loess") + 
 scale_y_reverse() + 
 labs(
  title = "Search ranking improved after schema implementation", 
  subtitle = "Previously, average ranking was decreasing", 
  y = "Average search rank"
 ) + 
 theme_minimal()
```

## Queries

```{r}
queries %>% 
 ggplot(aes(x = CTR, y = Position)) + 
 geom_point(alpha = .6) + 
 labs(
  title = "FL Law Help is often ranked very highly in searches", 
  subtitle = "Highly ranked searches have extremely varying click-through rates"
 ) +
 theme_minimal()
```

Queries with the highest click-through rates: 

```{r}
queries %>% 
 top_n(5, wt = CTR) %>% 
 arrange(desc(`CTR`)) %>% 
 select(Query, CTR, everything())
```

Queries where Law Help is in the first position: 

```{r}
queries %>% 
 top_n(-5, wt = Position) %>% 
 arrange(Position) %>% 
 select(Query, Position, everything())
```


## Recommendation

Pages with high traffic (many clicks), but low click-through rate: 

```{r}
pages %>% 
 top_n(20, Clicks) %>% 
 arrange(CTR)
```

